# Day 4: Giant Squid

You're already almost 1.5km (almost a mile) below the surface of the ocean, already so deep that you can't see any sunlight. What you can see, however, is a giant squid that has attached itself to the outside of your submarine.

Maybe it wants to play bingo?

Bingo is played on a set of boards each consisting of a 5x5 grid of numbers. Numbers are chosen at random, and the chosen number is marked on all boards on which it appears. (Numbers may not appear on all boards.) If all numbers in any row or any column of a board are marked, that board wins. (Diagonals don't count.)

The submarine has a bingo subsystem to help passengers (currently, you and the giant squid) pass the time. It automatically generates a random order in which to draw numbers and a random set of boards (your puzzle input). For example:


    7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

    22 13 17 11  0
     8  2 23  4 24
    21  9 14 16  7
     6 10  3 18  5
     1 12 20 15 19

     3 15  0  2 22
     9 18 13 17  5
    19  8  7 25 23
    20 11 10 24  4
    14 21 16 12  6

    14 21 17 24  4
    10 16 15  9 19
    18  8 23 26 20
    22 11 13  6  5
     2  0 12  3  7

After the first five numbers are drawn (7, 4, 9, 5, and 11), there are no winners, but the boards are marked as follows (shown here adjacent to each other to save space):

    22 13 17 11  0         3 15  0  2 22        14 21 17 24  4
     8  2 23  4 24         9 18 13 17  5        10 16 15  9 19
    21  9 14 16  7        19  8  7 25 23        18  8 23 26 20
     6 10  3 18  5        20 11 10 24  4        22 11 13  6  5
     1 12 20 15 19        14 21 16 12  6         2  0 12  3  7

After the next six numbers are drawn (17, 23, 2, 0, 14, and 21), there are still no winners:

    22 13 17 11  0         3 15  0  2 22        14 21 17 24  4
     8  2 23  4 24         9 18 13 17  5        10 16 15  9 19
    21  9 14 16  7        19  8  7 25 23        18  8 23 26 20
     6 10  3 18  5        20 11 10 24  4        22 11 13  6  5
     1 12 20 15 19        14 21 16 12  6         2  0 12  3  7

Finally, 24 is drawn:

    22 13 17 11  0         3 15  0  2 22        14 21 17 24  4
     8  2 23  4 24         9 18 13 17  5        10 16 15  9 19
    21  9 14 16  7        19  8  7 25 23        18  8 23 26 20
     6 10  3 18  5        20 11 10 24  4        22 11 13  6  5
     1 12 20 15 19        14 21 16 12  6         2  0 12  3  7

At this point, the third board wins because it has at least one complete row or column of marked numbers (in this case, the entire top row is marked: 14 21 17 24 4).

The score of the winning board can now be calculated. Start by finding the sum of all unmarked numbers on that board; in this case, the sum is 188. Then, multiply that sum by the number that was just called when the board won, 24, to get the final score, 188 * 24 = 4512.

To guarantee victory against the giant squid, figure out which board will win first. What will your final score be if you choose that board?


In [41]:
# import libs
import numpy as np

# import example data
example_seq = np.loadtxt('day4_example.txt', delimiter=',', max_rows=1)
example_cards = np.loadtxt('day4_example.txt', skiprows=2)

# import puzzle data
input_seq = np.loadtxt('day4_input.txt', delimiter=',', max_rows=1)
input_cards = np.loadtxt('day4_input.txt', skiprows=2)

In [44]:
def make_cards(arr):
    '''reshapes 1d arr into 3d arr of 5x5 bingo cards'''
    num_cards = int(len(arr)/5)
    return np.reshape(arr, (num_cards, 5, 5))

In [45]:
# reshape into bingo cards
example_cards = make_cards(example_cards)
input_cards = make_cards(input_cards)


## Data shapes

In [3]:
example_seq

array([ 7.,  4.,  9.,  5., 11., 17., 23.,  2.,  0., 14., 21., 24., 10.,
       16., 13.,  6., 15., 25., 12., 22., 18., 20.,  8., 19.,  3., 26.,
        1.])

In [4]:
example_cards

array([[[22., 13., 17., 11.,  0.],
        [ 8.,  2., 23.,  4., 24.],
        [21.,  9., 14., 16.,  7.],
        [ 6., 10.,  3., 18.,  5.],
        [ 1., 12., 20., 15., 19.]],

       [[ 3., 15.,  0.,  2., 22.],
        [ 9., 18., 13., 17.,  5.],
        [19.,  8.,  7., 25., 23.],
        [20., 11., 10., 24.,  4.],
        [14., 21., 16., 12.,  6.]],

       [[14., 21., 17., 24.,  4.],
        [10., 16., 15.,  9., 19.],
        [18.,  8., 23., 26., 20.],
        [22., 11., 13.,  6.,  5.],
        [ 2.,  0., 12.,  3.,  7.]]])

## Possible operations

In [6]:
np.sum(example_cards, axis=2)
# sums cards horizontally 

array([[63., 61., 67., 42., 67.],
       [42., 62., 82., 69., 69.],
       [80., 69., 95., 57., 24.]])

In [7]:
np.sum(example_cards, axis=1)
# sums cards vertically

array([[58., 46., 77., 64., 55.],
       [65., 73., 46., 80., 60.],
       [66., 56., 80., 68., 55.]])

In [8]:
# example_cards[example_cards == 7] = None
# example_cards[example_cards == [[22., 13., 17., 11.,  0.]]] = None
# set to null - might be better as need to sum remainder of values for answer

In [9]:
np.isnan(example_cards).all(axis=2)
# checks each row if all are nan - need to check axis=1 and axis=2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [15]:
winner = np.isnan(example_cards).all(axis=2)
np.where(winner == True)
# returns index of card and row/column where all are nan

len(np.where(winner == True)[0])
# selects cards only, checks length - can check if still 0 or if a card has won after drawing each number


0

## Solution